### ISSUE TITLE
UX: Redesign login / register popup

### ISSUE THREAD

**Issue by myOmikron** [hopfenspace/Unciv#36]
Closing the login / register popup is no dangerous operation, it does not need to have a red close button. Would be much nicer to have an x in the right upper corner of the popup

**Comment by CrsiX** [comment]
Button is now blue. The X in the right upper corner is not expected for now, since it's not fitting into the overall design of the application. There's only one other item (a popup) that uses X for closing (in that case, it's on the left lower corner).

**Comment by myOmikron** [comment]
Ok. Blue is fine
